language: node_js
cache:
  yarn: true
  directories:
  - node_modules
env:
- NODE_ENV=test
deploy:
  provider: heroku
  api_key:
    secure: AM6tDSBBhy+WSzCDXbMXpZYN7zpD4RyP7zKrkV9Cz5kkLQLp+2gRc9M9Hls1ikoej6bBEkerr/tMoUGKqQNmM7Z7PXfv/Gqaea4Mg1+++F6gfTgs1L1A7WlND5yfjKRydot1FAGmy2cJ1IxcSXg/WunO6voxiJt+rI0XRur1CbVdJZkhUM+pE/IQoRs4tys9Yq4s1Xg+kq6Rz7ctQ+jp2QMXRT6ggA1TlwK5KLYH7G3hxvuUqu9JVOROFToCAOgMzEqGQUZ37AhARrEm5w4vTcA6l7LT2PLyMJd5UTkXrRk8F4U+vFMvnRypbib2+7igbeVblEcE/5wuuK3jEtBdNRb3PSRDz/kN17DXtFDXAmo8GFDxhWEIEacj3YgCqXTOOa1kJsn/OHzqK9sHWihkWUoesPYP4BoGBeL4LBW7iFymQ02m6T/4TTbItNNrA17AdvlepyuPrROgAtV3aa2XFnRnv6RpsIHeWC98eC7j7Xhg1qGUO6INbsxjQ/L/rViIEUpAx0Zfybxhxy1ZAWOpX2h6IazPFHbsIT1rzl1bFz/6HArtrXbeND1EqEIE7pBO1T9wsXqzABi4coSM1C41cqVx+DB+c4C+fwzpjilVXLZ1wk7cq6zOVCpBLlEaOOxMwVnXrTzdg14jSdFplKgiC33P9uCcSb8R9taPqR73nwQ=
  app: coinaly
  on:
    repo: jvandenaardweg/coinaly
