language: node_js
cache:
  yarn: true
  directories:
  - node_modules
env:
- NODE_ENV=test
deploy:
  provider: heroku
  api_key:
    secure: X6/+/BDEXbFm1KBW+W3u/0KNXdou/8mvkwUO0My+/Nj2cwgSbbbIE63MwcJZhm3jdT3kq3dFIYFL3j9hwPmb/bn6TVH7Vf8mOHCTdBaTIkRcVvga8GemmnPKadCQyaKrHxSk6+DL5R7VYS1FWUBFVnfqw2TCD4R9l8ZD/6sb8jZhbx+/VS+VJfHcVnH3Y9almMQsgQBZF0E/klYqncA6yueXfyVspNdVJ2lw94g4b5bcnIVrZOu3eWefpjtsGrrarSLnYdN08YP4UoVfcWt+FL/FDJL/4TkRH0nP+BHqsudfmKj6z/fSKsjRjczEtLjpH3mS6ONYk99HTFkW7pQiLORaEl2Yd2zy2xL6mWhDDtmAeIqMo/HWy9yErRoYKTetdhcOfyze1T7D1D5vtECAPbtWLTefSUCcx35zT6Xt+KpgHwi/xa9dRJGoH8482qr8wkXpPSDrzoBvZCzFhRBzEzGya+SNji1JmJ8xLcKE7kgnHbjztF4DskloebRRIr/kJs6IXF68f7hz4IuF/EhA7rIr2j3Xj3eozyvCLujbzrj+45LHKpwGWxMvFdC6XUzaElGfvB2KAy3pXL5IxENSr/H+K1ApndsLYai0aJxr0+a6zZUjm+sll0zaSHuvAwJhsASyYH1FX9CIsDI6mZxcTqS4/dim1trol6Lq4zUiJ4A=
